version: '3'

services:
    backend:
        image: python
        volumes:
            - ./backend:/backend
        ports:
            - 5000:5000
        command: bash -c "cd /backend && pip install -r requirements.txt && flask run"

    frontend:
        image: nginx
        volumes:
            - ./frontend:/usr/share/nginx/html/
        ports:
            - 80:80
