version: '3'

services:

# --------------------------BACKEND----------------------------------------
    backend:
        build: ./backend
        ports:
            - 5000:5000

# --------------------------FRONTEND ---------------------------------------      
    frontend:
        # build: ./frontend
        image: node

        volumes:
            - ./frontend:/home/frontend
    
        command: bash -c "cd /home/frontend && npm run dev"
        ports:
            - 3000:3000

