version: '3'

services:

# --------------------------BACKEND----------------------------------------
    backend:
        container_name: backend
        build: ./backend
        ports:
            - 80:5000

# --------------------------BACKEND----------------------------------------
    # nginx:
    #     build: ./nginx
    #     container_name: nginx
    #     restart: always
    #     ports:
    #     - "80:80"

# --------------------------FRONTEND ---------------------------------------      
    # frontend:
    #     # build: ./frontend
    #     image: node

    #     volumes:
    #         - ./frontend:/home/frontend
    
    #     command: bash -c "cd /home/frontend && npm run dev"
    #     ports:
    #         - 3000:3000

